version: 2.1

jobs:
  test:
    macos:
      xcode: 13.2.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path .vendor
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - .vendor
      - run:
          name: fastlane
          command: bundle exec fastlane test
      - store_test_results:
          path: fastlane

workflows:
  version: 2
  basic-workflow:
    jobs:
      - test
